### ISSUE TITLE
I've met an error when runing 'python3 RefineNet/multi_gpu_train.py'

### ISSUE THREAD

**Issue by licaizi** [eragonruan/refinenet#8]
`Traceback (most recent call last):
  File "RefineNet/multi_gpu_train.py", line 245, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "RefineNet/multi_gpu_train.py", line 83, in main
    color_map = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)
`

**Comment by licaizi** [comment]
it's been solved

**Comment by Liusandian** [comment]
> it's been solved

how did your solved the question? could you offer more detail of the solution?Thanks

**Comment by licaizi** [comment]
@Liusandian sorry, it's been a long time, i can't remember its details, but probably due to the coding conflict, you may check your coding rules to make sure the codings of strings to be same.

Bests
